<?php
/**
 * Demo AddressComplete
 * @author Sam Schmidt <samuel@dersam.net>
 * @since 2016-01-27
 */

?>

<div class="input-line">
    <label for="street-address">Address</label>
    <input id="street-address" type="text" placeholder="Street address" autofocus />
</div>
<div class="input-line">
    <label for="street-address2"></label>
    <input id="street-address2" type="text" placeholder="" />
</div>
<div class="input-line">
    <label for="city"></label>
    <input id="city" type="text" placeholder="City" />
</div>
<div class="input-line">
    <label for="state"></label>
    <input id="state" type="text" placeholder="State/Province" />
</div>
<div class="input-line">
    <label for="postcode"></label>
    <input id="postcode" type="text" placeholder="Zip/Postcode" />
</div>
<div class="input-line">
    <label for="country"></label>
    <input id="country" type="text" placeholder="Country" />
</div>
