<?php
/**
 * Frontend template for the D2PO office pins on map
 *
 * @author Sam Schmidt <samuel@dersam.net>
 * @since 2016-02-05
 */
?>

<div class="canadapost marker">
    <span class="office-name">{{data.name}}</span> <br/>
    <span class="office-address">{{data.address.office_address}}</span> <br/>
    <span class="office-city">{{data.address.city}}, </span>
    <span class="office-province">{{data.address.province}}</span>
    <span class="office-postal">{{data.address.postal_code}}</span>
    <div class="office-info">
        <a class="office-info-external-url" href="<?= Mage::helper('linus_canadapost')->getCanadaPostOfficeUrl('{{% print(data["office-id"]) }}') ?>">
            <?= $this->__('View details and directions') ?>
        </a>
    </div>
</div>
