<?php
/**
 * Frontend template for the D2PO office pins on map
 *
 * @author Sam Schmidt <samuel@dersam.net>
 * @since 2016-02-05
 */
?>

<div class="canadapost marker">
    <span class="office-name">{{name}}</span> <br/>
    <span class="office-address">{{address.office_address}}</span> <br/>
    <span class="office-city">{{address.city}}, </span>
    <span class="office-province">{{address.province}}</span>
    <span class="office-postal">{{address.postal_code}}</span>
</div>
